### ISSUE TITLE
hello how do I run this config without losing all my hair

### ISSUE THREAD

**Issue by NotAShelf** [Gerg-L/nixos#382]
hi hello I want to copy your config but I don't want to become bald like you

what should I do?

thanks

**Comment by NotAShelf** [comment]
https://en.wikipedia.org/wiki/Hairy_frog

not you, obviously

**Comment by NotAShelf** [comment]
bald frog

**Comment by FrothyMarrow** [comment]
!endorse

**Comment by NotAShelf** [comment]
unbelivable

**Comment by Gerg-L** [comment]
No

**Comment by NotAShelf** [comment]
Heartbroken...
